# This resource configuration is intentionally invalid.
# It provides both 'name' and 'source_file', which are mutually exclusive
# according to the logic in the provider's 'plan' method.
#
# Running `terraform plan` should fail and display the error message
# generated by `ctx.add_error()` in the resource implementation.

# resource "pyvider_warning_example" "bad_config" {
#   name        = "a-direct-name"
#   source_file = "/etc/hostname"
# }
